#!/bin/bash
# REV04: Sun 17 Sep 2023 08:00
# REV03: Sun 23 Feb 2020 15:00
# REV02: Thu  6 Feb 2020 22:00
# START: Thu 17 Jan 2019 11:00
 
# Copyright (C) 2019-2023 BinKadal, Sdn. Bhd.
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# INFO: UTS 2019-1 (midterm)
INFO="../ZADMIN/zzz-generate-READ-THIS-FIRST.sh"
echo "";
[ -f $INFO ] && bash $INFO $0

TIGA=3
ANGKA="1 2 \$TIGA" #\$TIGA is not expanded here because of the backslash (\)
echo "START"
echo "ANGKA"
echo "$ANGKA"

echo ""
echo "gawk, try to find pattern /TIGA/"
echo "$ANGKA" | gawk '/TIGA/ {print $1, $2}' # here we pipe ANGKA to gawk and search for TIGA; /TIGA/ is a pattern to search for
echo ""

echo "gawk, try to find pattern /3/"
echo "$ANGKA" | gawk '/3/ {print $1, $2}' # here we pipe ANGKA to gawk and search for 3
echo ""

echo "gawk, try to find pattern /$TIGA/ using -v VAR=$TIGA"
# -v is called "assign", assigns value of TIGA to gawk variable VAR
# here we pipe ANGKA to gawk and search for variable TIGA; -v VAR=$TIGA is used to pass shell variable TIGA to gawk variable VAR
echo "$ANGKA" | gawk -v VAR=$TIGA '$3 == VAR {print $1, $2}' 

# here we pipe ANGKA to gawk and search for variable TIGA; -v VAR=$TIGA is used to pass shell variable TIGA to gawk variable VAR
echo "$ANGKA" | gawk -v VAR=$TIGA '$3 != VAR {print $1, $2}' 

echo "STOP"
exit 0

