#!/bin/bash
# REV04: Sun 17 Sep 2023 08:00
# REV03: Sun 23 Feb 2020 15:00
# REV02: Thu  6 Feb 2020 22:00
# REV01: Thu  6 Feb 2020 17:00
# START: Fri 25 Oct 2019 13:00

# Copyright (C) 2019-2023 BinKadal, Sdn. Bhd.
# This free document is distributed in the hope that it will be 
# useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# INFO: UTS 2019-2 (midterm)
INFO="../ZADMIN/zzz-generate-READ-THIS-FIRST.sh"
echo "";
[ -f $INFO ] && bash $INFO $0

LINE1="= BEGIN"
LINE2="TESTING regex using awk"
LINE3="TESTING REGEX using awk"
LINE4="= = END"

echo $LINE1

echo ""
echo "Trying to match 'regex' from LINE2 and LINE3 using awk"
echo $LINE2 | awk '/regex/{print $1}' # try to match 'regex' from LINE2

echo ""
echo "Trying to match 'regex' from LINE3 using awk"
echo $LINE3 | awk '/regex/{print $1}' # try to match 'regex' from LINE3

echo ""
echo "Trying to match 'regex' from LINE2 using tr to convert to lowercase"
echo $LINE2 | tr [A-Z] [a-z] | awk '/regex/{print $1}' # try to match 'regex' from LINE2 (lowercase)

echo "" 
echo "Trying to match 'regex' from LINE3 using tr to convert to lowercase"
echo $LINE3 | tr [A-Z] [a-z] | awk '/regex/{print $1}' # try to match 'regex' from LINE3 (lowercase)

echo ""
echo $LINE4

# Conclusion: awk is case-sensitive. To perform a case-insensitive match, convert the input to a common case (e.g., lowercase) using tr before passing it to awk.
# tr can also be used to convert to uppercase using tr [a-z] [A-Z]

exit 0


