#!/bin/bash
# REV03: Sun 17 Sep 2023 08:00
# REV02: Mon 12 Oct 2020 11:00
# REV01: Thu 12 Mar 2020 10:00
# START: Sun 26 Jan 2020 13:00
# FileName: 20-uts201

# Copyright (C) 2020-2023 BinKadal, Sdn. Bhd.
# This free document is distributed in the hope that it will be 
# useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# INFO: UTS 2020-1 (midterm)
# INFO:     What is the output of:
# INFO:        bash a20-uts201
# INFO:        bash a20-uts201 a20-uts201
INFO="../ZADMIN/zzz-generate-READ-THIS-FIRST.sh"
echo "";
[ -f $INFO ] && bash $INFO $0
echo "========= ========= ========= ========= ========= ========= ========= ========="

function INFO() {
   if [ -z "$1" ] # if no argument is given, -z means "is zero length"
   then
      printf "Script Name: $SCRIPT\n"
   else if [ -e "$1" ] # if argument is given and the file exists, -e means "file exists"
      then
         RESULT=$(grep "$PREFIX" "$1") # grep searches for the pattern in the file, it takes two arguments: pattern and file, returns the matching line
         if [ ! -z "$RESULT" ] # if RESULT is not empty, -z means "is zero length"
         then
            printf "[$SCRIPT] $RESULT\n"
         fi
      fi
   fi
}

PREFIX="^# FileName: "
SCRIPT="$0"
INFO "$1"
exit 0


